version: '3'

services:
  web:
    container_name: php-apache
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 9000:80

  db:
    container_name: Mini_Drive
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: MYSQL_DATABASE
        MYSQL_USER: Marrouche
        MYSQL_PASSWORD: password
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: unless-stopped
    environment:
        PMA_HOST: db
    depends_on:
        - db
volumes:
    db_data: